# Generated by Django 5.0.4 on 2024-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSection',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('verbose_name', models.CharField(blank=True)),
                ('capacity', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_places', models.SmallIntegerField(default=0)),
                ('created_photo_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.parkingsection')),
            ],
            options={
                'ordering': ['-created_photo_at'],
                'get_latest_by': 'created_photo_at',
            },
        ),
    ]
